settings:
  security_content_detection_path: ~/security_content/detections
  attack_data_dir_path: ~/attack_data
  output_dir_name : output
  cache_replay_yaml_name : cache_replay_data.yml
  replayed_yaml_cache_dir_name: replayed_yaml_cache
  debug_print: True

# Splunk connection settings
# Set these values in a .env file or as environment variables:
#   SPLUNK_HOST, SPLUNK_USERNAME, SPLUNK_PASSWORD, SPLUNK_HEC_TOKEN
splunk:
  host: ""
  username: ""
  password: ""
  hec_token: ""
