settings:
  security_content_detection_path: ~/security_content/detections
  attack_data_dir_path: ~/attack_data
  output_dir_name : output
  cache_replay_yaml_name : cache_replay_data.yml
  replayed_yaml_cache_dir_name: replayed_yaml_cache
  debug_print: True

# Splunk connection settings
# Environment variables (SPLUNK_HOST, SPLUNK_USERNAME, SPLUNK_PASSWORD, SPLUNK_HEC_TOKEN)
# will override these values if set
splunk:
  host: attack-data
  username: admin
  password: seamlesslabs
  hec_token: f9d2e13d-63ca-4bf2-8dcb-aa3a9d7dafff
